# Schema for the configuration files of the message module.

message.type.*:
  type: mapping
  label: 'Message type category'
  mapping:
    id:
      type: string
      label: 'Machine-readable name'
    uuid:
      type: string
      label: 'UUID'
    label:
      type: label
      label: 'Label'
    description:
      type: text
      label: 'Description'
    langcode:
      type: string
      label: 'Default language'
    text:
      type: sequence
      label: 'Default value'
      sequence:
        - type: string
          label: 'Message text'
    data:
      type: string
      label: 'Data'
