# Schema for the configuration files of the message module.

message.type.*:
  type: mapping
  label: 'Message type'
  mapping:
    type:
      type: string
      label: 'Machine-readable name'
    uuid:
      type: string
      label: 'UUID'
    label:
      type: label
      label: 'Label'
    category:
      type: string
      label: 'Category'
    description:
      type: text
      label: 'Description'
    langcode:
      type: string
      label: 'Language'

message.category.*:
  type: mapping
  label: 'Message category'
  mapping:
    type:
      type: string
      label: 'Machine-readable name'
    uuid:
      type: string
      label: 'UUID'
    label:
      type: label
      label: 'Label'
    description:
      type: text
      label: 'Description'
    langcode:
      type: string
      label: 'Language'
