# Schema for the configuration files of the message module.

message.type.*:
  type: config_entity
  label: 'Message type category'
  mapping:
    type:
      type: string
      label: 'Machine-readable name'
    label:
      type: label
      label: 'Label'
    description:
      type: text
      label: 'Description'
    text:
      type: mapping
      label: 'Message Text'
    data:
      type: mapping
      label: 'Data'
